import "./globals.css";
import type { Metadata } from "next";
import { Nunito } from "next/font/google";
import { Header } from "../components/Header/Header.jsx";
import { Footer } from "../components/Footer/Footer.jsx";

const nunito = Nunito({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Flix",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <main>
          <Header/>
          {children}
        </main>
      </body>
    </html>
  );
}
